packages:
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bcrypt
  - core-js
  - core-js-pure
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
